language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
install:
  - npm install -g firebase-tools
before_script:
  - npm install -g bower polymer-cli
  - bower install
script:
  - xvfb-run polymer test
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}
